version: "3.9"
services:
  mysql-server:
    networks:
      - default
    build:
      context: ./dockerfiles
      dockerfile: mysql-server
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10

  application:
    networks:
      - default
    build:
      context: ./dockerfiles
      dockerfile: application
    depends_on:
      mysql-server:
        condition: service_healthy
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
